server:
  port: 2000
spring:
  application:
    name: gateway

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.109.10:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: false

management:
  endpoints:
    web:
      exposure:
        include: '*'