server:
  port: 2000
spring:
  application:
    name: yifan-colud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: yifan.server:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: false
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 8722
        clientIp: 10.4.105.92
  redis:
    host: yifan.server
    port: 6379
application:
  security:
    oauth:
      ignored:
        - '/yifan-oauth-server/**'
management:
  endpoints:
    web:
      exposure:
        include: '*'



