server:
  port: 6002
spring:
  session:
    store-type: redis
  application:
    name: yifan-oauth-server
  redis:
    host: 10.4.105.95
    port: 6379
  datasource:
    url: jdbc:mysql://10.4.105.95:3306/oauth-center?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  cloud:
    nacos:
      discovery:
        server-addr: 10.4.105.95:8848
application:
  security:
    oauth:
      login-processing-url: /oauth/login

logging:
  level:
    org:
      springframework:
        security: debug