server:
  port: 2001
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: yifan.server:8848
  redis:
    host: yifan.server
    port: 6379
security:
  oauth2:
    resource:
      token-info-uri: http://127.0.0.1:6002/oauth/check_token
      user-info-uri:  http://127.0.0.1:6002/user
    client:
      access-token-uri: http://127.0.0.1:6002/oauth/token
      client-id: oauth2
      client-secret: oauth2
application:
  security:
    oauth:
      ignored:
        - '/yifan-oauth-server/**'
management:
  endpoints:
    web:
      exposure:
        include: '*'
zuul:
  routes:
    yifan-oauth-server:
      path: /yifan-oauth-server/**
      serviceId: yifan-oauth-server