server:
    port: 8000
spring:
    application:
        name: service-a
    cloud:
        nacos:
            discovery:
                server-addr: yifan.server.com:8848
        sentinel:
            transport:
                dashboard: yifan.server.com:8089
                port: 8719

management:
    endpoints:
        web:
            exposure:
                include: '*'
