server:
    port: 8000
spring:
    application:
        name: service-a
    cloud:
        inetutils:
            preferred-networks: 10.4
            ignored-interfaces: VMware*
        nacos:
            discovery:
                server-addr: yifan.server:8848
        sentinel:
            transport:
                dashboard: 127.0.0.1:8080
                port: 8719
                clientIp: 10.4.105.92
            #开启懒加载
            eager: true
            datasource:
                ns:
                    nacos:
                        serverAddr: ${spring.cloud.nacos.discovery.server-addr}
                        dataId: ${spring.application.name}-flow-rules
                        groupId: SENTINEL_GROUP
                        rule_type: flow
                        dataType: json
management:
    endpoints:
        web:
            exposure:
                include: '*'