server:
  port: 6003
spring:
  redis:
    host: 192.168.109.10
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.109.10:8848
  application:
    name: yifan-resource-server
logging:
  level:
    org.springframework.security: debug